// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

public type Course record {
    string name?;
    string code?;
    string nqfLevel?;
};

public type Programme record {
    string code?;
    string nqfLevel?;
    string faculty?;
    string department?;
    string title?;
    string registrationDate?;
    Course[] courses?;
};
