openapi: 3.0.0
info:
  title: Programme Management API
  version: 1.0.0
paths:
  /programme:
    post:
      summary: Add a new programme
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Programme'
      responses:
        '201':
          description: Created
    get:
      summary: Retrieve a list of all programmes
      responses:
        '200':
          description: A list of programmes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Programme'
  /programme/{code}:
    get:
      summary: Retrieve programme details by code
      parameters:
        - name: code
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A programme
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Programme'
    put:
      summary: Update programme information
      parameters:
        - name: code
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Programme'
      responses:
        '200':
          description: Updated
    delete:
      summary: Delete a programme by code
      parameters:
        - name: code
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Deleted
  /programme/reviewDue:
    get:
      summary: Retrieve all programmes due for review
      responses:
        '200':
          description: A list of programmes due for review
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Programme'
  /programme/faculty/{faculty}:
    get:
      summary: Retrieve all programmes by faculty
      parameters:
        - name: faculty
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A list of programmes by faculty
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Programme'
components:
  schemas:
    Programme:
      type: object
      properties:
        code:
          type: string
        nqfLevel:
          type: string
        faculty:
          type: string
        department:
          type: string
        title:
          type: string
        registrationDate:
          type: string
        courses:
          type: array
          items:
            $ref: '#/components/schemas/Course'
    Course:
      type: object
      properties:
        name:
          type: string
        code:
          type: string
        nqfLevel:
          type: string
